### ISSUE TITLE
RuntimeError: Function MmBackward0 returned an invalid gradient at index 1 - expected device meta but got cuda:0

### ISSUE THREAD

**Issue by wangjvjie** [ymcui/Chinese-LLaMA-Alpaca#734]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 由于相关依赖频繁更新，请确保按照[Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki)中的相关步骤执行
- [X] 我已阅读[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)、[LlamaChat](https://github.com/alexrozanski/LlamaChat)等，同时建议到对应的项目中查找解决方案
- [X] 模型正确性检查：务必检查模型的[SHA256.md](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/SHA256.md)，模型不对的情况下无法保证效果和正常运行

### 问题类型

模型训练与精调

### 基础模型

Alpaca-Plus-13B

### 操作系统

Linux

### 详细描述问题

我在微调sft的时候遇到了RuntimeError: Function MmBackward0 returned an invalid gradient at index 1 - expected device meta but got cuda:0，我在训练pretrain的时候没有遇到过，我看了整个代码除了DataCollatorForSupervisedDataset不一样之外，和pretrain没什么不一样。很奇怪为什么会出现这个错误？还有这个build_dataset的padding似乎并没有正常padding，input ids的长度是三百多。
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca/assets/82298975/bf2f5104-c9f7-4d67-ab5d-53d0f3434a5a)

我的训练脚本是这个，没有使用deepspeed因为我想用模型并行，而用deepspeed他好像会把所有peft或者数据之类的东西都加载到cuda0上面，没法正常训练，请问：
```
lr=1e-4
lora_rank=8
lora_alpha=32
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=../merged_llama_model/13B-hf/
chinese_tokenizer_path=./merged_tokenizer_hf
dataset_dir=../sft_vicuna/
per_device_train_batch_size=1
per_device_eval_batch_size=1
gradient_accumulation_steps=1
output_dir=./sft_lora/
peft_model=./pretrain/pt_lora_model
dataset_type="alpaca"

export CUDA_VISIBLE_DEVICES=0,1,2,3
python run_sft_finetune.py \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --dataset_type ${dataset_type} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --do_eval False \
    --seed 662 \
    --fp16 False\
    --num_train_epochs 1 \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --evaluation_strategy steps \
    --eval_steps 100 \
    --save_steps 200 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length 2048 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --modules_to_save ${modules_to_save} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float32 \
    --peft_path ${peft_model} \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```
